# ----------- 构建阶段 -----------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app

# 复制 csproj 并还原依赖
COPY *.csproj ./
RUN dotnet restore

# 复制所有源文件
COPY . ./

# 发布为自包含应用，目标平台 linux-x64
RUN dotnet publish -c Release -r linux-x64 --self-contained true \ 
  /p:PublishSingleFile=true \
  /p:IncludeAllContentForSelfExtract=true \
  /p:EnableCompressionInSingleFile=true \
  -o /app/publish

# ----------- 运行阶段 -----------
# 赋予执行权限（如果是 Linux 环境）
RUN chmod +x emby_crack

FROM scratch

LABEL maintainer="2017fighting"

# 拷贝已发布的文件
# copy local files
COPY root/ /
COPY --from=build /app/publish /usr