<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>emby_crack</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InformationalVersion>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss")) UTC</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>

</Project>
